task: Structure_kfold

training:
  gpu_device: 3
  batch_size: 1
  num_workers: 4
  seed: 42
  lr: 5.e-4
  weight_decay: 1.e-2
  max_epochs: 200
  warm_epochs: 10
  patience: 10
  lr_scheduler: cosine
  lr_decay_steps: 100
  lr_decay_rate: 0.5
  lr_decay_min_lr: 1.e-6
  log_dir: logs/finetune/Structure_kfold
  save_dir: model_weights/finetune/Structure_kfold
  vis_dir: vis/finetune/Structure_kfold/6r2l.trunc.fit

pretrained_model:
  epitope_model_path: model_weights/pretrained/EpitopeEncoder.pt
  tcra_model_path: model_weights/pretrained/TCRAEncoder.pt
  tcrb_model_path: model_weights/pretrained/TCRBEncoder.pt
  mhc_model_path: model_weights/pretrained/MHCEncoder.pt
  pmhc_model_path: model_weights/pretrained/pMHCFusion.pt
  tcrab_model_path: model_weights/pretrained/TCRABFusion.pt

MHCEncoder:
  num_layers: 6
  in_dim: 45
  embed_dim: 256
  mhc_len: 34

EpitopeEncoder:
  num_layers: 6
  in_dim: 20
  embed_dim: 256
  esm_dim: 1280
  epitope_len: 15 

TCRAEncoder:
  num_layers: 6
  in_dim: 45
  embed_dim: 256
  esm_dim: 1280
  cdr3_len: 38
  fv_len: 145

TCRBEncoder:
  num_layers: 6
  in_dim: 45
  embed_dim: 256
  esm_dim: 1280
  cdr3_len: 38
  fv_len: 140

pMHCFusion:
  num_layers: 6
  embed_dim: 256

TCRABFusion:
  num_layers: 6
  embed_dim: 256

StructureFinetuner:
  embed_dim: 256
  dropout: 0.3
  num_layers: 6

data: 
  data_path: data/structure/TCR3d_actual.csv
  pep_emb_path: data/pretrained_emb/pepesm
  TCRA_emb_path: data/pretrained_emb/tcr_a
  TCRB_emb_path: data/pretrained_emb/tcr_b
  structure_path: data/structure/true_structure
  max_epitope_len: 15
  max_mhc_len: 34
  max_TCRA_fv: 145
  max_TCRA_cdr: 38
  max_TCRB_fv: 140
  max_TCRB_cdr: 38